### ISSUE TITLE
Add the option to account for the dash/dock vertical size when resizing

### ISSUE THREAD

**Issue by visvital** [acristoffers/gnome-rectangle#2]
### Story
As a user, I want to be able to enable the option to account for the size of the dock/dash when resizing the windows, so that I could see the windows better aligned to the working area (especially, if  I prefer to keep the dock visible in some configurations).

### Acceptance criteria
1. The extension introduces the setting to account for the dock size when calculating the vertical space.
2. When the user applies the option, the extension excludes the dash/dock area when performing non-full-screen actions (moving to right/left, centering, etc.).

### Notes
1. This could be added as the set of the additional hotkeys or a settings item. 
2. In case, it is unwanted to interact with dash-to-dock, dash-to-panel extensions, it would be okay to just provide an input for the dock items size.
3. Overall, this option would just allow to align things a little bit better visually.

**Comment by acristoffers** [comment]
Thank you for the issue report.

Gnome adjusts the workspace area to account for some docks (like the Ubuntu one), but not for others, so instead of writing code to account for each possible dock one may want to use I went with the configurable in settings route. The new version is already available in Gnome Extensions website.
